{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.1.jar",
          "url": "spring-boot-starter-web-3.2.1.jar",
          "size": 4802,
          "sha512": "2fcfc8d9abfcd0518b6755737c6e520544600b3c26b42b60d1ab3fcfceb31582d5dbcd5d86a98ec312442d335e49f0db0ecf21d8e99089ef41d962ece42d97ae",
          "sha256": "2f14d3a4a0ae3ad634bcfa07117542001c1789c0bdce3504baee8f2bc45ef006",
          "sha1": "e27e36d4222fd4d589e634e1c7f5f09f0316147c",
          "md5": "8a6aea9e1fbdbabbd00e35038739200f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.1.jar",
          "url": "spring-boot-starter-web-3.2.1.jar",
          "size": 4802,
          "sha512": "2fcfc8d9abfcd0518b6755737c6e520544600b3c26b42b60d1ab3fcfceb31582d5dbcd5d86a98ec312442d335e49f0db0ecf21d8e99089ef41d962ece42d97ae",
          "sha256": "2f14d3a4a0ae3ad634bcfa07117542001c1789c0bdce3504baee8f2bc45ef006",
          "sha1": "e27e36d4222fd4d589e634e1c7f5f09f0316147c",
          "md5": "8a6aea9e1fbdbabbd00e35038739200f"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.1.jar",
          "url": "spring-boot-starter-web-3.2.1.jar",
          "size": 4802,
          "sha512": "2fcfc8d9abfcd0518b6755737c6e520544600b3c26b42b60d1ab3fcfceb31582d5dbcd5d86a98ec312442d335e49f0db0ecf21d8e99089ef41d962ece42d97ae",
          "sha256": "2f14d3a4a0ae3ad634bcfa07117542001c1789c0bdce3504baee8f2bc45ef006",
          "sha1": "e27e36d4222fd4d589e634e1c7f5f09f0316147c",
          "md5": "8a6aea9e1fbdbabbd00e35038739200f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.1.jar",
          "url": "spring-boot-starter-web-3.2.1.jar",
          "size": 4802,
          "sha512": "2fcfc8d9abfcd0518b6755737c6e520544600b3c26b42b60d1ab3fcfceb31582d5dbcd5d86a98ec312442d335e49f0db0ecf21d8e99089ef41d962ece42d97ae",
          "sha256": "2f14d3a4a0ae3ad634bcfa07117542001c1789c0bdce3504baee8f2bc45ef006",
          "sha1": "e27e36d4222fd4d589e634e1c7f5f09f0316147c",
          "md5": "8a6aea9e1fbdbabbd00e35038739200f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-web-3.2.1-javadoc.jar",
          "size": 4741,
          "sha512": "ee158e42335d0f9ba770c740f4534dd0a049d3852ac74ce0f2341c8c623215773db7b9abd58b058213d764533057122a47cab49cb309688b95d81d69e40f2cd4",
          "sha256": "982cb0c9fcf4fd2a8ed383e82c4a6c6f6dbac8728805be41a8b4c95231fe73ef",
          "sha1": "bb7bb0e2e8a123fa069cc15ab4de90f29dd59646",
          "md5": "72981a8f3001b9c49b089ab908c757a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.2.1-sources.jar",
          "url": "spring-boot-starter-web-3.2.1-sources.jar",
          "size": 4739,
          "sha512": "b7e4d42aba2fadbf2acacfa3c5fde93c409dd0a39f88b6a749a792474ede9008e6a55e5ba0a6ac92808f7004092fa815ec1c0bc7daa1ae30e8d614f07f0c768d",
          "sha256": "d19cb0de89c10b6dbfe100a217a69911809f9c684ce75bc7409f5f77383514d7",
          "sha1": "4f4403088253d3f8d30997b062c974d6d559ca18",
          "md5": "99062c32c1bd4cd1eb1e862867d14843"
        }
      ]
    }
  ]
}
