{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.2.1.jar",
          "url": "spring-boot-autoconfigure-3.2.1.jar",
          "size": 1922627,
          "sha512": "42bc3a99f9c9ffc9fd08447303a946fce1c81e3a869a5788c7d3b669536455eedc8009428ae4660d66b0d74ab170968b6aad905455b53342d7c521e7ec4c262f",
          "sha256": "371f0f36d226a8db972c37c73f0a0896ee4d3e77c29b54dbce8a64af731a6e53",
          "sha1": "b100d2d21d45dddd740d496357ca6f3813d777d0",
          "md5": "29fb14fe1d383588e87a73da4508604d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.2.1.jar",
          "url": "spring-boot-autoconfigure-3.2.1.jar",
          "size": 1922627,
          "sha512": "42bc3a99f9c9ffc9fd08447303a946fce1c81e3a869a5788c7d3b669536455eedc8009428ae4660d66b0d74ab170968b6aad905455b53342d7c521e7ec4c262f",
          "sha256": "371f0f36d226a8db972c37c73f0a0896ee4d3e77c29b54dbce8a64af731a6e53",
          "sha1": "b100d2d21d45dddd740d496357ca6f3813d777d0",
          "md5": "29fb14fe1d383588e87a73da4508604d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.2.1.jar",
          "url": "spring-boot-autoconfigure-3.2.1.jar",
          "size": 1922627,
          "sha512": "42bc3a99f9c9ffc9fd08447303a946fce1c81e3a869a5788c7d3b669536455eedc8009428ae4660d66b0d74ab170968b6aad905455b53342d7c521e7ec4c262f",
          "sha256": "371f0f36d226a8db972c37c73f0a0896ee4d3e77c29b54dbce8a64af731a6e53",
          "sha1": "b100d2d21d45dddd740d496357ca6f3813d777d0",
          "md5": "29fb14fe1d383588e87a73da4508604d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-autoconfigure-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.2.1.jar",
          "url": "spring-boot-autoconfigure-3.2.1.jar",
          "size": 1922627,
          "sha512": "42bc3a99f9c9ffc9fd08447303a946fce1c81e3a869a5788c7d3b669536455eedc8009428ae4660d66b0d74ab170968b6aad905455b53342d7c521e7ec4c262f",
          "sha256": "371f0f36d226a8db972c37c73f0a0896ee4d3e77c29b54dbce8a64af731a6e53",
          "sha1": "b100d2d21d45dddd740d496357ca6f3813d777d0",
          "md5": "29fb14fe1d383588e87a73da4508604d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-autoconfigure-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.2.1-javadoc.jar",
          "url": "spring-boot-autoconfigure-3.2.1-javadoc.jar",
          "size": 3019668,
          "sha512": "a5ba22bb400115e1d3d4cdffe4d59a1896f3a3b97b7a368ea2bc6064ebc7341bc61d130d288677ab4456e701544230d46bc9949de165aafd16359d24ee1467db",
          "sha256": "5443d0b12ac0e5af9ff745108b8b33bd8d536ebed9a619150163eff9772f65cb",
          "sha1": "ae44fc81f5c4fa960a0ff40d3116f3f6e512e83f",
          "md5": "42483330614f9e09fc291a3d7015613b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.2.1-sources.jar",
          "url": "spring-boot-autoconfigure-3.2.1-sources.jar",
          "size": 1118344,
          "sha512": "790737ab94536d4d93e215f0ecaf1b66598a1489d95845b4804ee2b9bc0ee3b1c7ae45214ebde0db437afc5e28f5d5c0eac341b6d10c09e8c786d978314c33e0",
          "sha256": "e1a43999d461ef95ba93449562f4e54c282de1604637674a7ef9b2b7e9755a55",
          "sha1": "94badb4b6a3a94510470d256681c6c8733209840",
          "md5": "db4e660102fee3dd1ef505a6578d3386"
        }
      ]
    }
  ]
}
