{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.17"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.17"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.17"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.2.1.jar",
          "url": "spring-boot-starter-tomcat-3.2.1.jar",
          "size": 4791,
          "sha512": "d2bce5bb0271525766283e17160513de530c20e0452cecc3c9d5be3890986cc071c1423a3c11c54a36d2f83bd3a238b0fcbcc6218976a5633f0753a313418f6f",
          "sha256": "bf93da73a8fb4caf9fa68e4f3b97adcc9dbb8c79220a828b3d70ecf12d410117",
          "sha1": "d8efc48034015522958cb3fea5831b4cbcd4fcfb",
          "md5": "db4df0f653e84bfd545894c4567b19ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.17"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.17"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.17"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.2.1.jar",
          "url": "spring-boot-starter-tomcat-3.2.1.jar",
          "size": 4791,
          "sha512": "d2bce5bb0271525766283e17160513de530c20e0452cecc3c9d5be3890986cc071c1423a3c11c54a36d2f83bd3a238b0fcbcc6218976a5633f0753a313418f6f",
          "sha256": "bf93da73a8fb4caf9fa68e4f3b97adcc9dbb8c79220a828b3d70ecf12d410117",
          "sha1": "d8efc48034015522958cb3fea5831b4cbcd4fcfb",
          "md5": "db4df0f653e84bfd545894c4567b19ff"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.2.1.jar",
          "url": "spring-boot-starter-tomcat-3.2.1.jar",
          "size": 4791,
          "sha512": "d2bce5bb0271525766283e17160513de530c20e0452cecc3c9d5be3890986cc071c1423a3c11c54a36d2f83bd3a238b0fcbcc6218976a5633f0753a313418f6f",
          "sha256": "bf93da73a8fb4caf9fa68e4f3b97adcc9dbb8c79220a828b3d70ecf12d410117",
          "sha1": "d8efc48034015522958cb3fea5831b4cbcd4fcfb",
          "md5": "db4df0f653e84bfd545894c4567b19ff"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.2.1.jar",
          "url": "spring-boot-starter-tomcat-3.2.1.jar",
          "size": 4791,
          "sha512": "d2bce5bb0271525766283e17160513de530c20e0452cecc3c9d5be3890986cc071c1423a3c11c54a36d2f83bd3a238b0fcbcc6218976a5633f0753a313418f6f",
          "sha256": "bf93da73a8fb4caf9fa68e4f3b97adcc9dbb8c79220a828b3d70ecf12d410117",
          "sha1": "d8efc48034015522958cb3fea5831b4cbcd4fcfb",
          "md5": "db4df0f653e84bfd545894c4567b19ff"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.2.1-javadoc.jar",
          "size": 4742,
          "sha512": "9773555d90f753e9072473f89e7b0c86a24724ffbe41b55256d49f9de21957d4e32b3f222c5a4aa23fe08d3c0765b3701c32f02bc1b56a6745dbaea4ed84c54d",
          "sha256": "9645ed261bcec9bb0672b12d3952601cd68491b80c8a98a26b1e074f9428847e",
          "sha1": "791475a60c183c33486a633ec6e0623e87bb5d22",
          "md5": "bdf7e011327444b721799b9b46438296"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.2.1-sources.jar",
          "url": "spring-boot-starter-tomcat-3.2.1-sources.jar",
          "size": 4740,
          "sha512": "b5434ebe8c5a6eb4cd40ffa83da404a74863a29d43d06b029d1eb4fab8942f2b9fb614504c075703076b207d1fede78ce18cc0e5f5f32b911a9b9a9167a6ffeb",
          "sha256": "8e038453c0d8a95c70fdf917dec8858df2c85e9bcd9c02aac371d44d254b83e1",
          "sha1": "94c1387e17a3a479ae99f2d8d6afaf4c3532c9a2",
          "md5": "dd188bd0088413b58dbaf26653b9c795"
        }
      ]
    }
  ]
}
