{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.17"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.1.jar",
          "url": "spring-boot-starter-validation-3.2.1.jar",
          "size": 4766,
          "sha512": "b4d50b005cf9ac0dea24f7ebb056001e5e4842199e9afab328e424465e796f809c74a26f9d06e726999ee00f314adb9740a5b47ac5965576faf1d392c318d517",
          "sha256": "b882b6b6bedc7dcd7f8c9a0068263c1a6faa48c55467dc4a3859fe62531b7b30",
          "sha1": "54a35ea1de2c7de2c701e93740228240218cc9dd",
          "md5": "9cfb47fafa1e59b6490d4578b82afde2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.17"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.1.jar",
          "url": "spring-boot-starter-validation-3.2.1.jar",
          "size": 4766,
          "sha512": "b4d50b005cf9ac0dea24f7ebb056001e5e4842199e9afab328e424465e796f809c74a26f9d06e726999ee00f314adb9740a5b47ac5965576faf1d392c318d517",
          "sha256": "b882b6b6bedc7dcd7f8c9a0068263c1a6faa48c55467dc4a3859fe62531b7b30",
          "sha1": "54a35ea1de2c7de2c701e93740228240218cc9dd",
          "md5": "9cfb47fafa1e59b6490d4578b82afde2"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.1.jar",
          "url": "spring-boot-starter-validation-3.2.1.jar",
          "size": 4766,
          "sha512": "b4d50b005cf9ac0dea24f7ebb056001e5e4842199e9afab328e424465e796f809c74a26f9d06e726999ee00f314adb9740a5b47ac5965576faf1d392c318d517",
          "sha256": "b882b6b6bedc7dcd7f8c9a0068263c1a6faa48c55467dc4a3859fe62531b7b30",
          "sha1": "54a35ea1de2c7de2c701e93740228240218cc9dd",
          "md5": "9cfb47fafa1e59b6490d4578b82afde2"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.1.jar",
          "url": "spring-boot-starter-validation-3.2.1.jar",
          "size": 4766,
          "sha512": "b4d50b005cf9ac0dea24f7ebb056001e5e4842199e9afab328e424465e796f809c74a26f9d06e726999ee00f314adb9740a5b47ac5965576faf1d392c318d517",
          "sha256": "b882b6b6bedc7dcd7f8c9a0068263c1a6faa48c55467dc4a3859fe62531b7b30",
          "sha1": "54a35ea1de2c7de2c701e93740228240218cc9dd",
          "md5": "9cfb47fafa1e59b6490d4578b82afde2"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-validation-3.2.1-javadoc.jar",
          "size": 4744,
          "sha512": "c7c3aa9b747f7752b01befe6bad7c06de6daa2c8646adb8e2c1311abf175623edaa2e1b37aac9b925bdec0a22240d3148f2fbc41c8e23692ab88eda5ce0fe28d",
          "sha256": "14b0b4202c4ff30e1b4db1148c8ad04127c24dae59fe32fbf79b4dce1e41428a",
          "sha1": "426ba8144c7158ea0dd24b8d1a818fc3ffb41d97",
          "md5": "42be59a9f5e26e30eba523f486d2e0a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.1-sources.jar",
          "url": "spring-boot-starter-validation-3.2.1-sources.jar",
          "size": 4742,
          "sha512": "f677b972d1d3ad5d4f5872aec28314d1c11914835bdfb9ac29c591ef9c769961e538137ba249f57c0fa5efff6a1c2cf74aba536588be748f6f0029630a6cc8c5",
          "sha256": "393ab057faceff141b2c27831ea158cfdef681ffff5f2073ef831085311493db",
          "sha1": "fc5848f4cb611707ab16d020a6ca40d8baddbc20",
          "md5": "f88459623ef0cb1e5d56f4907b3433ff"
        }
      ]
    }
  ]
}
