{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.23.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.2.1.jar",
          "url": "spring-boot-loader-tools-3.2.1.jar",
          "size": 432679,
          "sha512": "3f232acfc04ee0f68db7fafa5099aadb3f3b9d737369c6bd0cd5a399cd404a8c0d5c08da0533660ae217a27289a8cd2e7c77afcfd832688c7dd09a932ad9b11c",
          "sha256": "54c21bb84eccd89f2b52bbace5a8cffbe68ae050a5956f89f24f7acb830dce85",
          "sha1": "6ba39183f70565a39395094af94dbb97cb684c65",
          "md5": "d64c8d8a275a63badcb513d285646505"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.23.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.2.1.jar",
          "url": "spring-boot-loader-tools-3.2.1.jar",
          "size": 432679,
          "sha512": "3f232acfc04ee0f68db7fafa5099aadb3f3b9d737369c6bd0cd5a399cd404a8c0d5c08da0533660ae217a27289a8cd2e7c77afcfd832688c7dd09a932ad9b11c",
          "sha256": "54c21bb84eccd89f2b52bbace5a8cffbe68ae050a5956f89f24f7acb830dce85",
          "sha1": "6ba39183f70565a39395094af94dbb97cb684c65",
          "md5": "d64c8d8a275a63badcb513d285646505"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.2.1-javadoc.jar",
          "url": "spring-boot-loader-tools-3.2.1-javadoc.jar",
          "size": 251069,
          "sha512": "613df656b8830c491c4de25090cec9542a8bd5cbf901658cebd099637eacea0f135f7e918c3d573378d4ff1466fe0975ea04c94f73b02e418cb198e7fca4ad44",
          "sha256": "ceb424e9c16e3590344f6e420438eae9669cd9909ed7d4f128f0787abd33c80f",
          "sha1": "29496b7487e68543b8765d4af53b1bd9ad1dfedc",
          "md5": "dd8cfe7e970e18944a291ac2f989fcda"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.2.1-sources.jar",
          "url": "spring-boot-loader-tools-3.2.1-sources.jar",
          "size": 74898,
          "sha512": "efa018aa60ef463f6b6b0428494544bc28e7e415a7e9f6cde9eb118a45cc175c30031c842a7567fc8e5c289f0516f8760b80b4add526f23dbff7f118cc59a3fb",
          "sha256": "913a92130b3ac4da00d25a30917d1005531aad4395e826dfd4f6ee7a41ad0895",
          "sha1": "5fb57245992537d0aaba3584a61793081dab035d",
          "md5": "fd474c1a4803475b3637bfca2d393ede"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.2.1.jar",
          "url": "spring-boot-loader-tools-3.2.1.jar",
          "size": 432679,
          "sha512": "3f232acfc04ee0f68db7fafa5099aadb3f3b9d737369c6bd0cd5a399cd404a8c0d5c08da0533660ae217a27289a8cd2e7c77afcfd832688c7dd09a932ad9b11c",
          "sha256": "54c21bb84eccd89f2b52bbace5a8cffbe68ae050a5956f89f24f7acb830dce85",
          "sha1": "6ba39183f70565a39395094af94dbb97cb684c65",
          "md5": "d64c8d8a275a63badcb513d285646505"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.2.1.jar",
          "url": "spring-boot-loader-tools-3.2.1.jar",
          "size": 432679,
          "sha512": "3f232acfc04ee0f68db7fafa5099aadb3f3b9d737369c6bd0cd5a399cd404a8c0d5c08da0533660ae217a27289a8cd2e7c77afcfd832688c7dd09a932ad9b11c",
          "sha256": "54c21bb84eccd89f2b52bbace5a8cffbe68ae050a5956f89f24f7acb830dce85",
          "sha1": "6ba39183f70565a39395094af94dbb97cb684c65",
          "md5": "d64c8d8a275a63badcb513d285646505"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "3.2.1"
        }
      ]
    }
  ]
}
