{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.2.1.jar",
          "url": "spring-boot-starter-3.2.1.jar",
          "size": 4767,
          "sha512": "35cc80f9b10e81624324083a024c97e247e12f54762cfaadf40504903b0ebdc76d0226af1e4646bca445211b039913709ff48289dd57e27ecab18fd6e427d306",
          "sha256": "a25f2f4172c34f46b73fff03293370c3daf231a1db2883ef8032aa471779fb8b",
          "sha1": "bc03d7075fb9d9d4877218db48d5dae3dd72a65d",
          "md5": "d9eb815815944bcdaeed5e63f32e5d7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.2.1.jar",
          "url": "spring-boot-starter-3.2.1.jar",
          "size": 4767,
          "sha512": "35cc80f9b10e81624324083a024c97e247e12f54762cfaadf40504903b0ebdc76d0226af1e4646bca445211b039913709ff48289dd57e27ecab18fd6e427d306",
          "sha256": "a25f2f4172c34f46b73fff03293370c3daf231a1db2883ef8032aa471779fb8b",
          "sha1": "bc03d7075fb9d9d4877218db48d5dae3dd72a65d",
          "md5": "d9eb815815944bcdaeed5e63f32e5d7f"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.1.jar",
          "url": "spring-boot-starter-3.2.1.jar",
          "size": 4767,
          "sha512": "35cc80f9b10e81624324083a024c97e247e12f54762cfaadf40504903b0ebdc76d0226af1e4646bca445211b039913709ff48289dd57e27ecab18fd6e427d306",
          "sha256": "a25f2f4172c34f46b73fff03293370c3daf231a1db2883ef8032aa471779fb8b",
          "sha1": "bc03d7075fb9d9d4877218db48d5dae3dd72a65d",
          "md5": "d9eb815815944bcdaeed5e63f32e5d7f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.1.jar",
          "url": "spring-boot-starter-3.2.1.jar",
          "size": 4767,
          "sha512": "35cc80f9b10e81624324083a024c97e247e12f54762cfaadf40504903b0ebdc76d0226af1e4646bca445211b039913709ff48289dd57e27ecab18fd6e427d306",
          "sha256": "a25f2f4172c34f46b73fff03293370c3daf231a1db2883ef8032aa471779fb8b",
          "sha1": "bc03d7075fb9d9d4877218db48d5dae3dd72a65d",
          "md5": "d9eb815815944bcdaeed5e63f32e5d7f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-3.2.1-javadoc.jar",
          "size": 4734,
          "sha512": "3fb2bd366ebab9747dc42c8825121c1c938bc0dd907e0434e24316989dcacba73b9f5298d0ec78afe27e4f5a8dea12bdb69622d5fa85543bcb37b22bde8be6bb",
          "sha256": "8ce9795004ed040ced3b5a6bfaa634c9f457991872b92b58440d7c71e9f852eb",
          "sha1": "c832f56371304855736442107d71527bb43ccc9a",
          "md5": "3aab7369d8b2006486db4e2ff99bca4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.1-sources.jar",
          "url": "spring-boot-starter-3.2.1-sources.jar",
          "size": 4733,
          "sha512": "89fc5cb8af8de8b864128c4fd3b7f91b19391f953bf7e493bb09173a6b0d4dfb6dbb2e13a6a3176ba5be1ca41b1cb9da197ba91b3d8b26462e6747ef01c5a5ef",
          "sha256": "34e252166990873094d7d88911ca3a0b9eddbe58fee55fe75d593af81d4b3595",
          "sha1": "84f6cc62430f30efc533dee832a0fd77ec4b031d",
          "md5": "cbfad778fbbb54a2ab5e16c45792f30e"
        }
      ]
    }
  ]
}
