{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.15.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.2.1.jar",
          "url": "spring-boot-starter-json-3.2.1.jar",
          "size": 4746,
          "sha512": "c611e0d07093d99dbcded7a00e7c00355a7c13c24a69d33105ca88ec63cc68ba76339b5a96b84f2b666bb883849980776e1e24ee2df9c7dd07b2dde0992289b5",
          "sha256": "572f1a4171dff33b5a9260bbd704473442adf24f890386abe33ecc18c047836a",
          "sha1": "ecda50de20ab6d3c49ea30df4c1982048f5d31ac",
          "md5": "bea54cf408b022894c0b1b013c58c0a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.15.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.2.1.jar",
          "url": "spring-boot-starter-json-3.2.1.jar",
          "size": 4746,
          "sha512": "c611e0d07093d99dbcded7a00e7c00355a7c13c24a69d33105ca88ec63cc68ba76339b5a96b84f2b666bb883849980776e1e24ee2df9c7dd07b2dde0992289b5",
          "sha256": "572f1a4171dff33b5a9260bbd704473442adf24f890386abe33ecc18c047836a",
          "sha1": "ecda50de20ab6d3c49ea30df4c1982048f5d31ac",
          "md5": "bea54cf408b022894c0b1b013c58c0a9"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.2.1.jar",
          "url": "spring-boot-starter-json-3.2.1.jar",
          "size": 4746,
          "sha512": "c611e0d07093d99dbcded7a00e7c00355a7c13c24a69d33105ca88ec63cc68ba76339b5a96b84f2b666bb883849980776e1e24ee2df9c7dd07b2dde0992289b5",
          "sha256": "572f1a4171dff33b5a9260bbd704473442adf24f890386abe33ecc18c047836a",
          "sha1": "ecda50de20ab6d3c49ea30df4c1982048f5d31ac",
          "md5": "bea54cf408b022894c0b1b013c58c0a9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.2.1.jar",
          "url": "spring-boot-starter-json-3.2.1.jar",
          "size": 4746,
          "sha512": "c611e0d07093d99dbcded7a00e7c00355a7c13c24a69d33105ca88ec63cc68ba76339b5a96b84f2b666bb883849980776e1e24ee2df9c7dd07b2dde0992289b5",
          "sha256": "572f1a4171dff33b5a9260bbd704473442adf24f890386abe33ecc18c047836a",
          "sha1": "ecda50de20ab6d3c49ea30df4c1982048f5d31ac",
          "md5": "bea54cf408b022894c0b1b013c58c0a9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-json-3.2.1-javadoc.jar",
          "size": 4741,
          "sha512": "7b1e49528af8f6407462b1e554be596089dbf9c6d48cf72fb4fcb78bec1edb87df26928d235ffb0a98ca82cf867868cfe4eb04b8136e8d0cea8a1cc12ab73807",
          "sha256": "97d980990678a8d70419a93e69bdbc7b1c6b6a233faefd5824d0738ba2760094",
          "sha1": "843fab5247e6709f3b9521cc939cf3acb153e2b4",
          "md5": "338e9c43b6f19a75ded9a02d12ebd03e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.2.1-sources.jar",
          "url": "spring-boot-starter-json-3.2.1-sources.jar",
          "size": 4740,
          "sha512": "737407ec07c596ee40aeafa6f5103837482b803fbc4e37ba15c61a1efd15058c120f8465a1bca41c9a9eac84f50de7fc6eb415bfed7cc397a7f9f5efdc97948c",
          "sha256": "5cae70d32f07059e45a6624f5589a118b3e73d00d514d1c82fb5b6ced39b45a5",
          "sha1": "405cb361d64986f22783c72d46f8429d04fbabef",
          "md5": "df13d0b2ab426ef03be1faaa2954954f"
        }
      ]
    }
  ]
}
