{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.2.1.jar",
          "url": "spring-boot-test-3.2.1.jar",
          "size": 245478,
          "sha512": "975428c3f753ec1375f9c0ca2c47756a22896cc510193b53f7a8501255634a2e0d2165e699055667f4127cbaa8e79c9c128aef6de0854fccd4e158dce4422939",
          "sha256": "0fb27aeb59ab757e60c48f9810d0ab54dc858a4c1cd9cc75b4ad07456c9c3e7c",
          "sha1": "142fbe3cfe3370c57d0ed55cca0d8d96e1d6f26e",
          "md5": "5c793b3b61ba2637840a6c865aa2901e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.2.1.jar",
          "url": "spring-boot-test-3.2.1.jar",
          "size": 245478,
          "sha512": "975428c3f753ec1375f9c0ca2c47756a22896cc510193b53f7a8501255634a2e0d2165e699055667f4127cbaa8e79c9c128aef6de0854fccd4e158dce4422939",
          "sha256": "0fb27aeb59ab757e60c48f9810d0ab54dc858a4c1cd9cc75b4ad07456c9c3e7c",
          "sha1": "142fbe3cfe3370c57d0ed55cca0d8d96e1d6f26e",
          "md5": "5c793b3b61ba2637840a6c865aa2901e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.2.1-javadoc.jar",
          "url": "spring-boot-test-3.2.1-javadoc.jar",
          "size": 413945,
          "sha512": "4dd000b7646a4fddd1af73a769fe60f52a344bc2f3b2b489f1cd016b4ea20b5115c62f91aee84b0843d51cbb3dcbaca1ff08751fdecb81d636274af8f809027e",
          "sha256": "f98aafd51a5e2b302973e84894359aae7320474a1f399dc8d68413d7cfe4f1d1",
          "sha1": "2c46c3f3466ea438462724f8aa2fd8240f78a0e7",
          "md5": "804fb19d9a2be16846028b8585df2e05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.2.1-sources.jar",
          "url": "spring-boot-test-3.2.1-sources.jar",
          "size": 168442,
          "sha512": "85f26e48bb85351c6e18c3d9d5a03a3dd31faef92751b4eb419d8d86e541d6d0ce54a2f5ff753ef8b76847da27239656766bb5a066d92d0bf65c94906c82a4f1",
          "sha256": "043452c5bde9abd270f0e7bead798a95b4feb047a5e4fcd7a47d7ef891816d81",
          "sha1": "849c2e6a162270f5468821dd357b930a6a01dfac",
          "md5": "5237754e522534b3d5619339129a20ca"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-3.2.1.jar",
          "url": "spring-boot-test-3.2.1.jar",
          "size": 245478,
          "sha512": "975428c3f753ec1375f9c0ca2c47756a22896cc510193b53f7a8501255634a2e0d2165e699055667f4127cbaa8e79c9c128aef6de0854fccd4e158dce4422939",
          "sha256": "0fb27aeb59ab757e60c48f9810d0ab54dc858a4c1cd9cc75b4ad07456c9c3e7c",
          "sha1": "142fbe3cfe3370c57d0ed55cca0d8d96e1d6f26e",
          "md5": "5c793b3b61ba2637840a6c865aa2901e"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.2.1.jar",
          "url": "spring-boot-test-3.2.1.jar",
          "size": 245478,
          "sha512": "975428c3f753ec1375f9c0ca2c47756a22896cc510193b53f7a8501255634a2e0d2165e699055667f4127cbaa8e79c9c128aef6de0854fccd4e158dce4422939",
          "sha256": "0fb27aeb59ab757e60c48f9810d0ab54dc858a4c1cd9cc75b4ad07456c9c3e7c",
          "sha1": "142fbe3cfe3370c57d0ed55cca0d8d96e1d6f26e",
          "md5": "5c793b3b61ba2637840a6c865aa2901e"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "3.2.1"
        }
      ]
    }
  ]
}
