{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-tx",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.1.2.jar",
          "url": "spring-tx-6.1.2.jar",
          "size": 284249,
          "sha512": "ccf386086adf940077189c7d48985dbdef2fc15356abb23856901b72060a4b085cd7b6e39da73ca64c52370adf54777a8fa1222b1b9281e835b2659cfc2aefc4",
          "sha256": "6d5105951018b36c0bcfbfdeac8d0eb6aafa1988d77de2a897f618fb0da489c2",
          "sha1": "48b9ff81c43345320779b402f1bb33b9f46ec4e9",
          "md5": "4df38f1a60ee15fc1604a6a0d3b5875b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.1.2.jar",
          "url": "spring-tx-6.1.2.jar",
          "size": 284249,
          "sha512": "ccf386086adf940077189c7d48985dbdef2fc15356abb23856901b72060a4b085cd7b6e39da73ca64c52370adf54777a8fa1222b1b9281e835b2659cfc2aefc4",
          "sha256": "6d5105951018b36c0bcfbfdeac8d0eb6aafa1988d77de2a897f618fb0da489c2",
          "sha1": "48b9ff81c43345320779b402f1bb33b9f46ec4e9",
          "md5": "4df38f1a60ee15fc1604a6a0d3b5875b"
        }
      ]
    }
  ]
}
