{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.1.jar",
          "url": "spring-boot-test-autoconfigure-3.2.1.jar",
          "size": 219071,
          "sha512": "701b6ee27c87081e4a65ba76fe721f74e917a655575b19b9205b314f4a561889564e09ceadaa880aaf30f70cd8b48dc70fc5e32f511204b1ea031a12349fd9be",
          "sha256": "86c51c743babfc591be09af7fedcd778410706e567e9ed27218448ccd2297ef4",
          "sha1": "bfc34c523b3ab295fb01f46373e903f9729cdd43",
          "md5": "d6f93aa42df4cb27a58835750597d835"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.1.jar",
          "url": "spring-boot-test-autoconfigure-3.2.1.jar",
          "size": 219071,
          "sha512": "701b6ee27c87081e4a65ba76fe721f74e917a655575b19b9205b314f4a561889564e09ceadaa880aaf30f70cd8b48dc70fc5e32f511204b1ea031a12349fd9be",
          "sha256": "86c51c743babfc591be09af7fedcd778410706e567e9ed27218448ccd2297ef4",
          "sha1": "bfc34c523b3ab295fb01f46373e903f9729cdd43",
          "md5": "d6f93aa42df4cb27a58835750597d835"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.1-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-3.2.1-javadoc.jar",
          "size": 488295,
          "sha512": "96ec351558c69d7f134cda00c969fa7d03c2f1fa1e2fd4e8d0e2d095673a7b4dc8a3558c945e59562aa9971093a8257d4fffc36d04b9187c8ff250d17c42b092",
          "sha256": "bef1745c9c9ef214f314036b8be51888268eb9fe10622bd3516a476e4dadcd18",
          "sha1": "20536ec9ff2f8b70862a37dfb3d323e63162b7d4",
          "md5": "2f78efa2b890408d7cd93d26dd830843"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.1-sources.jar",
          "url": "spring-boot-test-autoconfigure-3.2.1-sources.jar",
          "size": 221355,
          "sha512": "846965573046fd7e54298814acd62c34ed5c89ea3db3d837b876e743e7175e3eddace44df911b7b7fdc1b364197465a758e4a97c2a5a46d51e60fe5a38815afa",
          "sha256": "5185aba2b1140339add5c708f451e03716739cf834cf1f9d58b7d8dbaccddaf6",
          "sha1": "258e382cf56b98f7ef5304585d35dfa8916e724c",
          "md5": "6f6d66519aa809a24f00a6db243a7edc"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.1.jar",
          "url": "spring-boot-test-autoconfigure-3.2.1.jar",
          "size": 219071,
          "sha512": "701b6ee27c87081e4a65ba76fe721f74e917a655575b19b9205b314f4a561889564e09ceadaa880aaf30f70cd8b48dc70fc5e32f511204b1ea031a12349fd9be",
          "sha256": "86c51c743babfc591be09af7fedcd778410706e567e9ed27218448ccd2297ef4",
          "sha1": "bfc34c523b3ab295fb01f46373e903f9729cdd43",
          "md5": "d6f93aa42df4cb27a58835750597d835"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.2.1.jar",
          "url": "spring-boot-test-autoconfigure-3.2.1.jar",
          "size": 219071,
          "sha512": "701b6ee27c87081e4a65ba76fe721f74e917a655575b19b9205b314f4a561889564e09ceadaa880aaf30f70cd8b48dc70fc5e32f511204b1ea031a12349fd9be",
          "sha256": "86c51c743babfc591be09af7fedcd778410706e567e9ed27218448ccd2297ef4",
          "sha1": "bfc34c523b3ab295fb01f46373e903f9729cdd43",
          "md5": "d6f93aa42df4cb27a58835750597d835"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "3.2.1"
        }
      ]
    }
  ]
}
