{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-actuator",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.1.jar",
          "url": "spring-boot-starter-actuator-3.2.1.jar",
          "size": 4804,
          "sha512": "ed618c7f1e3337c90919551ad4f14996bb2a78f773ba00c1e02d5a991d1c578e940d9b73f5e01045115c7b5d3f096f8de6720ba0d28992a586ef834948f17766",
          "sha256": "31c28021755feab49cc9310a8353382b3ca35d0adf02926b83e4c44ea4942898",
          "sha1": "ca17ff67e80a230f04d40d73321d623b769e361d",
          "md5": "59713236dc4fc4b1562a3ea9788bde1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.1.jar",
          "url": "spring-boot-starter-actuator-3.2.1.jar",
          "size": 4804,
          "sha512": "ed618c7f1e3337c90919551ad4f14996bb2a78f773ba00c1e02d5a991d1c578e940d9b73f5e01045115c7b5d3f096f8de6720ba0d28992a586ef834948f17766",
          "sha256": "31c28021755feab49cc9310a8353382b3ca35d0adf02926b83e4c44ea4942898",
          "sha1": "ca17ff67e80a230f04d40d73321d623b769e361d",
          "md5": "59713236dc4fc4b1562a3ea9788bde1e"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.1.jar",
          "url": "spring-boot-starter-actuator-3.2.1.jar",
          "size": 4804,
          "sha512": "ed618c7f1e3337c90919551ad4f14996bb2a78f773ba00c1e02d5a991d1c578e940d9b73f5e01045115c7b5d3f096f8de6720ba0d28992a586ef834948f17766",
          "sha256": "31c28021755feab49cc9310a8353382b3ca35d0adf02926b83e4c44ea4942898",
          "sha1": "ca17ff67e80a230f04d40d73321d623b769e361d",
          "md5": "59713236dc4fc4b1562a3ea9788bde1e"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-actuator-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.1.jar",
          "url": "spring-boot-starter-actuator-3.2.1.jar",
          "size": 4804,
          "sha512": "ed618c7f1e3337c90919551ad4f14996bb2a78f773ba00c1e02d5a991d1c578e940d9b73f5e01045115c7b5d3f096f8de6720ba0d28992a586ef834948f17766",
          "sha256": "31c28021755feab49cc9310a8353382b3ca35d0adf02926b83e4c44ea4942898",
          "sha1": "ca17ff67e80a230f04d40d73321d623b769e361d",
          "md5": "59713236dc4fc4b1562a3ea9788bde1e"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-actuator-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-actuator-3.2.1-javadoc.jar",
          "size": 4743,
          "sha512": "c9674227edc77e0aeae0fa8d3e17b3942300ae112bb1489f4a0d64afcb91c1cc9eeeedcd82ce40016d3d5457b0e8cd77a68bfd88cef83b5392984dd63a8575fd",
          "sha256": "f94a9a43744e09ce4fed3513496f32d193affc1ba275499b234c3cbd0eab7c88",
          "sha1": "95aa358d181263cb0dc32ebb60130a01f70191ed",
          "md5": "edd8f1863fae0950511cb9051ba58ae1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.1-sources.jar",
          "url": "spring-boot-starter-actuator-3.2.1-sources.jar",
          "size": 4742,
          "sha512": "cd97646146d8ccd47d6b831c893f7406eab561332648ba0bbb0813437f6d035bb4990ce1ae42226640a8c5a0bbe20026426b2d98373027a375fdeef535dcd04c",
          "sha256": "d830b634f2e3e6eb9cdf5a7dfdd3f7f345c912cab7c6d278a485de107dd2756a",
          "sha1": "0d7d87166178f1c9bc9db85cff75419f2199388e",
          "md5": "927d952220b818f89700a616a9ec5161"
        }
      ]
    }
  ]
}
