{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.2.1.jar",
          "url": "spring-boot-3.2.1.jar",
          "size": 1604001,
          "sha512": "8619959d143ef38f5c846591b8b10b0c50906a3301a5e9ed3e3df44124bdfbe3197cd4ecfb214c3250f40a0c1b11138b7a3f6865755445879f0685d2e88a6846",
          "sha256": "6fde604399114e77b12519b3d117117c607cb73b89a88800856fb0e0cc82ea7a",
          "sha1": "faa2ce019bee68a8d17529d0a08ebc427f927e13",
          "md5": "6f7384977eae04c804b1062df9217959"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.2.1.jar",
          "url": "spring-boot-3.2.1.jar",
          "size": 1604001,
          "sha512": "8619959d143ef38f5c846591b8b10b0c50906a3301a5e9ed3e3df44124bdfbe3197cd4ecfb214c3250f40a0c1b11138b7a3f6865755445879f0685d2e88a6846",
          "sha256": "6fde604399114e77b12519b3d117117c607cb73b89a88800856fb0e0cc82ea7a",
          "sha1": "faa2ce019bee68a8d17529d0a08ebc427f927e13",
          "md5": "6f7384977eae04c804b1062df9217959"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.2.1-javadoc.jar",
          "url": "spring-boot-3.2.1-javadoc.jar",
          "size": 2319987,
          "sha512": "c4446fb79427eb0b76d50f3a0f5472f8784c8ca504ea8bd1ef5a607f6436f3a9b0ffc33e6d75c9e294199fd41133b735d0cbfc23535f4744569d859f16a83b5f",
          "sha256": "04825aa54a7f994118c89c19d712a74a6b521c34daa3d32fec8e2a5b0b6f4d80",
          "sha1": "8bfcea559607b03caffd5cca2cf2794e82e96beb",
          "md5": "a8171abcc5e2a2285048b8bee6ade356"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.2.1-sources.jar",
          "url": "spring-boot-3.2.1-sources.jar",
          "size": 1105561,
          "sha512": "b24e3120a29cf99fff8a6235f35883e05a8971532822c32da8339288a728ac270266d9706784f7bc89db4f472317a9484c824ce9cb33b56be18443b9f0a602f5",
          "sha256": "78f414daee8dd54a70c1450c2fac8d54b0672a8d850d8f7c25eb4a7926b1ef04",
          "sha1": "b9c61bf839de72a061a8d51b91f5c81cd90cc66f",
          "md5": "769621ca9096ce53faae3035c739bd82"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-3.2.1.jar",
          "url": "spring-boot-3.2.1.jar",
          "size": 1604001,
          "sha512": "8619959d143ef38f5c846591b8b10b0c50906a3301a5e9ed3e3df44124bdfbe3197cd4ecfb214c3250f40a0c1b11138b7a3f6865755445879f0685d2e88a6846",
          "sha256": "6fde604399114e77b12519b3d117117c607cb73b89a88800856fb0e0cc82ea7a",
          "sha1": "faa2ce019bee68a8d17529d0a08ebc427f927e13",
          "md5": "6f7384977eae04c804b1062df9217959"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.2.1.jar",
          "url": "spring-boot-3.2.1.jar",
          "size": 1604001,
          "sha512": "8619959d143ef38f5c846591b8b10b0c50906a3301a5e9ed3e3df44124bdfbe3197cd4ecfb214c3250f40a0c1b11138b7a3f6865755445879f0685d2e88a6846",
          "sha256": "6fde604399114e77b12519b3d117117c607cb73b89a88800856fb0e0cc82ea7a",
          "sha1": "faa2ce019bee68a8d17529d0a08ebc427f927e13",
          "md5": "6f7384977eae04c804b1062df9217959"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "3.2.1"
        }
      ]
    }
  ]
}
