{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.resilience4j",
    "module": "resilience4j-core",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resilience4j-core-2.2.0.jar",
          "url": "resilience4j-core-2.2.0.jar",
          "size": 77587,
          "sha512": "e28246320120a2e62a154c3873fe5368fa8ef956f56b922a536c35bf85377feee19b43129d6fbf9a7ad126faad612a45f984cc4821737e3db62770f5f26ae6e1",
          "sha256": "6200917bb21c30134c27e3de8bc8c6e4a7760d87579a0dc4e2dc54888beab5ce",
          "sha1": "61b780cfbfbc41d7b8b26278ca3b81c034330457",
          "md5": "b611481f2f07e337aa9a3ea0fe30fa35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-core-2.2.0.jar",
          "url": "resilience4j-core-2.2.0.jar",
          "size": 77587,
          "sha512": "e28246320120a2e62a154c3873fe5368fa8ef956f56b922a536c35bf85377feee19b43129d6fbf9a7ad126faad612a45f984cc4821737e3db62770f5f26ae6e1",
          "sha256": "6200917bb21c30134c27e3de8bc8c6e4a7760d87579a0dc4e2dc54888beab5ce",
          "sha1": "61b780cfbfbc41d7b8b26278ca3b81c034330457",
          "md5": "b611481f2f07e337aa9a3ea0fe30fa35"
        }
      ]
    }
  ]
}
