{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator-autoconfigure",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.1.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.1.jar",
          "size": 749526,
          "sha512": "7197158ef14a580edc836ab7af10a9f5f567ba60e21267b624fc4143debd2638c7b8bd8e2e5973fdd5c5d512be73df96500fb0a4273f20a21b42161e9f7add75",
          "sha256": "3850d85c0f6074fe9286dece9b44f8bded5e194e9b816860735e0fc728173d65",
          "sha1": "0fe81034352a15731322fba326447ba70bfa3962",
          "md5": "3afea56b25f872cee2c929c761b0790d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.1.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.1.jar",
          "size": 749526,
          "sha512": "7197158ef14a580edc836ab7af10a9f5f567ba60e21267b624fc4143debd2638c7b8bd8e2e5973fdd5c5d512be73df96500fb0a4273f20a21b42161e9f7add75",
          "sha256": "3850d85c0f6074fe9286dece9b44f8bded5e194e9b816860735e0fc728173d65",
          "sha1": "0fe81034352a15731322fba326447ba70bfa3962",
          "md5": "3afea56b25f872cee2c929c761b0790d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.1.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.1.jar",
          "size": 749526,
          "sha512": "7197158ef14a580edc836ab7af10a9f5f567ba60e21267b624fc4143debd2638c7b8bd8e2e5973fdd5c5d512be73df96500fb0a4273f20a21b42161e9f7add75",
          "sha256": "3850d85c0f6074fe9286dece9b44f8bded5e194e9b816860735e0fc728173d65",
          "sha1": "0fe81034352a15731322fba326447ba70bfa3962",
          "md5": "3afea56b25f872cee2c929c761b0790d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-actuator-autoconfigure-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.1.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.1.jar",
          "size": 749526,
          "sha512": "7197158ef14a580edc836ab7af10a9f5f567ba60e21267b624fc4143debd2638c7b8bd8e2e5973fdd5c5d512be73df96500fb0a4273f20a21b42161e9f7add75",
          "sha256": "3850d85c0f6074fe9286dece9b44f8bded5e194e9b816860735e0fc728173d65",
          "sha1": "0fe81034352a15731322fba326447ba70bfa3962",
          "md5": "3afea56b25f872cee2c929c761b0790d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-actuator-autoconfigure-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.1-javadoc.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.1-javadoc.jar",
          "size": 1338134,
          "sha512": "083d9ef1cd1703170c34127c17e9a28545d61a1e2ee190ed5b214f7a2b9a9228ab98312db748fa5ed0258d3ad4a537e7ca0a6518e42fec1618239756ce23f667",
          "sha256": "0ed7adda6ea2a9e2182b54bae342a792dbb4704dc3e11b5abdb2624aa4e65266",
          "sha1": "90b8b3d8b90245c995c8c1fde04c4a41d9871186",
          "md5": "0afa5e5cb9b7c49a7d8f59aafe309fdd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.1-sources.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.1-sources.jar",
          "size": 533477,
          "sha512": "5d4f82a07a2466229f0b3e626bbb73322e5a00439784623e3cc48089684567eda29e343d12e8fed982457fbe573045eee8ef99de0e203965c535dcb1c3b51f54",
          "sha256": "3c169ce7998f1e9ffb9bd49ba47b53d56371a68645199c0ef618b633f5a1ed5c",
          "sha1": "8efbfea7ec0d1f9b66703feb8952b6dcfd8ea4f5",
          "md5": "1e9a5d66db36c05b5784e33fc8b6a1e8"
        }
      ]
    }
  ]
}
