{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.1.jar",
          "url": "spring-boot-gradle-plugin-3.2.1.jar",
          "size": 144668,
          "sha512": "6fc925cde85f87a009c346d76c22884655c49bfe5ce76473feddced9d4b339f4cbe85de449c6f355a33743bb40d01f627841afb126a987b66a5b15207af310e5",
          "sha256": "6772f0072c15c93c398bfcc96baf24b6ef7accaef20e305b4258e465e92535e1",
          "sha1": "b81576b25ad5fed9edb76bb7db5e0e7c37c92ae3",
          "md5": "988e28e1fe721077775acd2cc758a1fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.23.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.1.jar",
          "url": "spring-boot-gradle-plugin-3.2.1.jar",
          "size": 144668,
          "sha512": "6fc925cde85f87a009c346d76c22884655c49bfe5ce76473feddced9d4b339f4cbe85de449c6f355a33743bb40d01f627841afb126a987b66a5b15207af310e5",
          "sha256": "6772f0072c15c93c398bfcc96baf24b6ef7accaef20e305b4258e465e92535e1",
          "sha1": "b81576b25ad5fed9edb76bb7db5e0e7c37c92ae3",
          "md5": "988e28e1fe721077775acd2cc758a1fa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.1-javadoc.jar",
          "url": "spring-boot-gradle-plugin-3.2.1-javadoc.jar",
          "size": 319378,
          "sha512": "c48c88691657ffbbfcbd3704ef6e27b90893828624180c98227b503e1dfeba88a4da031ba33f9b5cf6ab0619e9afaf91c4aaaa2291a88b466ee41e4b7181ab49",
          "sha256": "e3934b50483846e529f73b682ce1da720e26179bd1ec12e9f23b7a5fae5f2f0b",
          "sha1": "1ff59b28b11e67b521f4523bee1fea43196c3994",
          "md5": "ce30e6b0857dc5c5a7559b27e1251143"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.1-sources.jar",
          "url": "spring-boot-gradle-plugin-3.2.1-sources.jar",
          "size": 81870,
          "sha512": "72d69b3fd77d4e504ab82fe207a69c4c1524fd9f2c533159ba06c2fff9fe8cd6efa2cad818870a26d205dea9010c66ba68a8a0530a1476ff23f849f4bc791e16",
          "sha256": "acfa3b1388dff75d00e58e62530be802362b363b91b76f33d3ced7b823c5c950",
          "sha1": "6a3db1be5a30ef2698458e29a0114ecc48ae6785",
          "md5": "98244314deb4dd0bc74fd993c26553e1"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.1.jar",
          "url": "spring-boot-gradle-plugin-3.2.1.jar",
          "size": 144668,
          "sha512": "6fc925cde85f87a009c346d76c22884655c49bfe5ce76473feddced9d4b339f4cbe85de449c6f355a33743bb40d01f627841afb126a987b66a5b15207af310e5",
          "sha256": "6772f0072c15c93c398bfcc96baf24b6ef7accaef20e305b4258e465e92535e1",
          "sha1": "b81576b25ad5fed9edb76bb7db5e0e7c37c92ae3",
          "md5": "988e28e1fe721077775acd2cc758a1fa"
        },
        {
          "name": "spring-boot-gradle-plugin-3.2.1.jar",
          "url": "spring-boot-gradle-plugin-3.2.1.jar",
          "size": 144668,
          "sha512": "6fc925cde85f87a009c346d76c22884655c49bfe5ce76473feddced9d4b339f4cbe85de449c6f355a33743bb40d01f627841afb126a987b66a5b15207af310e5",
          "sha256": "6772f0072c15c93c398bfcc96baf24b6ef7accaef20e305b4258e465e92535e1",
          "sha1": "b81576b25ad5fed9edb76bb7db5e0e7c37c92ae3",
          "md5": "988e28e1fe721077775acd2cc758a1fa"
        },
        {
          "name": "spring-boot-gradle-plugin-3.2.1.jar",
          "url": "spring-boot-gradle-plugin-3.2.1.jar",
          "size": 144668,
          "sha512": "6fc925cde85f87a009c346d76c22884655c49bfe5ce76473feddced9d4b339f4cbe85de449c6f355a33743bb40d01f627841afb126a987b66a5b15207af310e5",
          "sha256": "6772f0072c15c93c398bfcc96baf24b6ef7accaef20e305b4258e465e92535e1",
          "sha1": "b81576b25ad5fed9edb76bb7db5e0e7c37c92ae3",
          "md5": "988e28e1fe721077775acd2cc758a1fa"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-gradle-plugin-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.2.1.jar",
          "url": "spring-boot-gradle-plugin-3.2.1.jar",
          "size": 144668,
          "sha512": "6fc925cde85f87a009c346d76c22884655c49bfe5ce76473feddced9d4b339f4cbe85de449c6f355a33743bb40d01f627841afb126a987b66a5b15207af310e5",
          "sha256": "6772f0072c15c93c398bfcc96baf24b6ef7accaef20e305b4258e465e92535e1",
          "sha1": "b81576b25ad5fed9edb76bb7db5e0e7c37c92ae3",
          "md5": "988e28e1fe721077775acd2cc758a1fa"
        },
        {
          "name": "spring-boot-gradle-plugin-3.2.1.jar",
          "url": "spring-boot-gradle-plugin-3.2.1.jar",
          "size": 144668,
          "sha512": "6fc925cde85f87a009c346d76c22884655c49bfe5ce76473feddced9d4b339f4cbe85de449c6f355a33743bb40d01f627841afb126a987b66a5b15207af310e5",
          "sha256": "6772f0072c15c93c398bfcc96baf24b6ef7accaef20e305b4258e465e92535e1",
          "sha1": "b81576b25ad5fed9edb76bb7db5e0e7c37c92ae3",
          "md5": "988e28e1fe721077775acd2cc758a1fa"
        },
        {
          "name": "spring-boot-gradle-plugin-3.2.1.jar",
          "url": "spring-boot-gradle-plugin-3.2.1.jar",
          "size": 144668,
          "sha512": "6fc925cde85f87a009c346d76c22884655c49bfe5ce76473feddced9d4b339f4cbe85de449c6f355a33743bb40d01f627841afb126a987b66a5b15207af310e5",
          "sha256": "6772f0072c15c93c398bfcc96baf24b6ef7accaef20e305b4258e465e92535e1",
          "sha1": "b81576b25ad5fed9edb76bb7db5e0e7c37c92ae3",
          "md5": "988e28e1fe721077775acd2cc758a1fa"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-gradle-plugin-maven-optional",
          "version": "3.2.1"
        }
      ]
    }
  ]
}
