{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.2.1.jar",
          "url": "spring-boot-starter-logging-3.2.1.jar",
          "size": 4759,
          "sha512": "23baf0a59d56809db43101fbddb712b515012c64530362665cebe84c53bbd716218d3602024315f3250dea923138845c09d5c56dd9c7fb26a53d5e21a325e52e",
          "sha256": "0b7e411cfc44a15fc63a36cd05a73b34c3558f1b06e4f297b1919361b8a351a7",
          "sha1": "0df8ec78dc87885298998ca3c9bd603ee7bfe5b8",
          "md5": "7ac01b9dee045285c365cf6a3d8d8451"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.2.1.jar",
          "url": "spring-boot-starter-logging-3.2.1.jar",
          "size": 4759,
          "sha512": "23baf0a59d56809db43101fbddb712b515012c64530362665cebe84c53bbd716218d3602024315f3250dea923138845c09d5c56dd9c7fb26a53d5e21a325e52e",
          "sha256": "0b7e411cfc44a15fc63a36cd05a73b34c3558f1b06e4f297b1919361b8a351a7",
          "sha1": "0df8ec78dc87885298998ca3c9bd603ee7bfe5b8",
          "md5": "7ac01b9dee045285c365cf6a3d8d8451"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.2.1.jar",
          "url": "spring-boot-starter-logging-3.2.1.jar",
          "size": 4759,
          "sha512": "23baf0a59d56809db43101fbddb712b515012c64530362665cebe84c53bbd716218d3602024315f3250dea923138845c09d5c56dd9c7fb26a53d5e21a325e52e",
          "sha256": "0b7e411cfc44a15fc63a36cd05a73b34c3558f1b06e4f297b1919361b8a351a7",
          "sha1": "0df8ec78dc87885298998ca3c9bd603ee7bfe5b8",
          "md5": "7ac01b9dee045285c365cf6a3d8d8451"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-logging-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.2.1.jar",
          "url": "spring-boot-starter-logging-3.2.1.jar",
          "size": 4759,
          "sha512": "23baf0a59d56809db43101fbddb712b515012c64530362665cebe84c53bbd716218d3602024315f3250dea923138845c09d5c56dd9c7fb26a53d5e21a325e52e",
          "sha256": "0b7e411cfc44a15fc63a36cd05a73b34c3558f1b06e4f297b1919361b8a351a7",
          "sha1": "0df8ec78dc87885298998ca3c9bd603ee7bfe5b8",
          "md5": "7ac01b9dee045285c365cf6a3d8d8451"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-logging-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-logging-3.2.1-javadoc.jar",
          "size": 4743,
          "sha512": "a9fd171d62008b323582084432e21baf34cc9fa8d4ed530dc64d2a73c44ca78d0dc6275877b2defcf87dfe4f41bb375d1ad8e9a8a14c42e29a1e2200c9461490",
          "sha256": "5aefed84d6d30955c495902b3fb90fc1f3d0329e88f07e614dede0707ece9fed",
          "sha1": "1c8bf407d8a4ab045d570610f6af88b9c6786743",
          "md5": "f2a8b5b86438ea23575d299aa6db257c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.2.1-sources.jar",
          "url": "spring-boot-starter-logging-3.2.1-sources.jar",
          "size": 4741,
          "sha512": "c97c5323f6dc91351a1a681788a6b5d169e130fa381ab2090bd0b2585b1ff0212d896805aef77ef58c0644e9df55b967d6d8db2e306bdebc624b1aad43b8db74",
          "sha256": "bcdaf80a27f163cf367adce479e3ad2c0292cc19f60cff302e29f39c10a8447d",
          "sha1": "a6f38c3f1a64821a1bb2adde904d81c9849ce0e5",
          "md5": "5b41932f12866d31bd4b8e3df8b03920"
        }
      ]
    }
  ]
}
