{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.1.2.jar",
          "url": "spring-aop-6.1.2.jar",
          "size": 413914,
          "sha512": "b1cb69feb2931bd4af48b2329614f8e2a0d1afe77267af5f5ea9717ab24c83fd524c8bc7aa8d357a6ccbc497535c4fd282ddfb6d78364a349895a14825af8b9c",
          "sha256": "e47b66833ebec281374d55b4e36352b80fe3fa64c94252481a8a7e8d31d9d601",
          "sha1": "a247bd81df8fa9c6a002b95969692bfd146a70b2",
          "md5": "c9b8757051ed6c1cc9fda0e379283348"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.1.2.jar",
          "url": "spring-aop-6.1.2.jar",
          "size": 413914,
          "sha512": "b1cb69feb2931bd4af48b2329614f8e2a0d1afe77267af5f5ea9717ab24c83fd524c8bc7aa8d357a6ccbc497535c4fd282ddfb6d78364a349895a14825af8b9c",
          "sha256": "e47b66833ebec281374d55b4e36352b80fe3fa64c94252481a8a7e8d31d9d601",
          "sha1": "a247bd81df8fa9c6a002b95969692bfd146a70b2",
          "md5": "c9b8757051ed6c1cc9fda0e379283348"
        }
      ]
    }
  ]
}
