{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.23.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.10"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.2.1.jar",
          "url": "spring-boot-buildpack-platform-3.2.1.jar",
          "size": 272103,
          "sha512": "313b792fa7e18e5e2c100e54539cda0ec173bd141e966f9f81dcd8e239f5772a2519d5a4872a2c2466cf4495424a735d21e867f258e49a19ec3f63cbea7ff9b7",
          "sha256": "fcee3633979b1a16f5654819e1e2a12496bd6c1dab32771c303afe9f342eabe6",
          "sha1": "8f0cdda0eed451d703583acd4edbb8aede14bbf2",
          "md5": "612721da7d6fc641d75fa23f1f4ef75a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.23.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.10"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.2.1.jar",
          "url": "spring-boot-buildpack-platform-3.2.1.jar",
          "size": 272103,
          "sha512": "313b792fa7e18e5e2c100e54539cda0ec173bd141e966f9f81dcd8e239f5772a2519d5a4872a2c2466cf4495424a735d21e867f258e49a19ec3f63cbea7ff9b7",
          "sha256": "fcee3633979b1a16f5654819e1e2a12496bd6c1dab32771c303afe9f342eabe6",
          "sha1": "8f0cdda0eed451d703583acd4edbb8aede14bbf2",
          "md5": "612721da7d6fc641d75fa23f1f4ef75a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.2.1-javadoc.jar",
          "url": "spring-boot-buildpack-platform-3.2.1-javadoc.jar",
          "size": 394190,
          "sha512": "63f2d4e631531ffeda5b685a2208349903d7bc2cd3f91601727d00f6820f5501dc7b77bd33f50717228657c1371d3b9ee3450a9771e3382007473ddd1396eba9",
          "sha256": "2a8e635b12db75e4bc3b589346839d7171b752d7eff90fffa3a6b97aa0dad0a2",
          "sha1": "922b04ad3f9d8d9b830049fece615507e063f893",
          "md5": "0d6017adc8b00b06339dfa9e63a68d2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.2.1-sources.jar",
          "url": "spring-boot-buildpack-platform-3.2.1-sources.jar",
          "size": 169365,
          "sha512": "b84e92e3c37705f310a91b9207ab00bb8b47611abf2417d23361c747a93e759b7f25c62bd66dbfa45f422b87606a4ae5285005a9aa715c0ab2988719b72f6dd9",
          "sha256": "cbb4dd6d39d587293d53ebc92c66c33126462afcb9b080a2b7229dbd4dfa2a8b",
          "sha1": "56184663f975a49c79147a4229d339b91303b2a5",
          "md5": "093de20a592f03a503264a3cce802325"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.2.1.jar",
          "url": "spring-boot-buildpack-platform-3.2.1.jar",
          "size": 272103,
          "sha512": "313b792fa7e18e5e2c100e54539cda0ec173bd141e966f9f81dcd8e239f5772a2519d5a4872a2c2466cf4495424a735d21e867f258e49a19ec3f63cbea7ff9b7",
          "sha256": "fcee3633979b1a16f5654819e1e2a12496bd6c1dab32771c303afe9f342eabe6",
          "sha1": "8f0cdda0eed451d703583acd4edbb8aede14bbf2",
          "md5": "612721da7d6fc641d75fa23f1f4ef75a"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-buildpack-platform-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.2.1.jar",
          "url": "spring-boot-buildpack-platform-3.2.1.jar",
          "size": 272103,
          "sha512": "313b792fa7e18e5e2c100e54539cda0ec173bd141e966f9f81dcd8e239f5772a2519d5a4872a2c2466cf4495424a735d21e867f258e49a19ec3f63cbea7ff9b7",
          "sha256": "fcee3633979b1a16f5654819e1e2a12496bd6c1dab32771c303afe9f342eabe6",
          "sha1": "8f0cdda0eed451d703583acd4edbb8aede14bbf2",
          "md5": "612721da7d6fc641d75fa23f1f4ef75a"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-buildpack-platform-maven-optional",
          "version": "3.2.1"
        }
      ]
    }
  ]
}
